### ISSUE TITLE
Redirect uses the wrong letter for lemmy things (/m/ instead of /c/) in the url.

### ISSUE THREAD

**Issue by dredshep** [driccio98/kbin-link#2]
![image](https://github.com/driccio98/kbin-link/assets/78047001/870b6e7b-a8f9-41bd-ae23-35ebc8d0b451)

All urls as far as I can see have the wrong thingy at /m/ instead of /c/ (magazine vs community)

**Comment by daniel-lxs** [comment]
Use https://github.com/FackJox/lemmy-link for Lemmy :)

**Comment by daniel-lxs** [comment]
Solved in [fc65a60](https://github.com/driccio98/kbin-link/commit/fc65a605a028fef84f540033455c7b7d39a9fd4b)
