### ISSUE TITLE
Required Firefox version

### ISSUE THREAD

**Issue by RheingoldRiver** [driccio98/kbin-link#3]
Hello,
Do you really require Firefox 109 or later? I was a bit behind on versions so I just updated to install this, and it broke all my userChrome and I spent a couple hours fixing it, which is not my favorite thing to do.

Not your fault of course, but I wonder if you really require features from 109 or if you could be a bit more permissive in version requirements.

Either way, thanks so much for this extension, I look forward to using it! (and my userChrome is mostly fixed)

**Comment by daniel-lxs** [comment]
Sorry you had to do all that, yes, it is necessary because I'm using manifest v3 to make the extension compatible with chrome and firefox. 

I recommend only enabling the extension on the sites you expect to use it, as it might cause slowness on really big websites that update a lot.

**Comment by RheingoldRiver** [comment]
Ah, got it. No worries then!
